---
all:
  children:
    production_control:
      hosts:
        skinnypete:
          ansible_host: 100.105.164.64
          local_ip: 192.168.25.172
          ansible_user: heisenberg
          tailscale_autoroute: true
        hank:
          ansible_host: 100.79.51.33
          ansible_user: heisenberg
          tailscale_autoroute: true
        winchesterpi:
          ansible_host: 100.73.161.51
          ansible_user: bobstephen
          tailscale_autoroute: true
          location: "Winchester"

    openwrt_routers:
      hosts:
        winnebago:
          ansible_host: 192.168.8.1
          tailscale_ip: 100.93.112.62
          lan_ip: 192.168.8.1
          ansible_user: root
          location: "Travel"
        gl-ax1800:
          ansible_host: 100.121.163.68
          tailscale_ip: 100.121.163.68
          lan_ip: 192.168.25.1
          ansible_user: root
          location: "HMO"
        gl-ax1800-ap1:
          ansible_host: 192.168.25.167
          lan_ip: 192.168.25.167
          ansible_user: root
          location: "HMO"

    cloud_vms:
      hosts:
        vultr:
          ansible_host: 100.90.33.88
          public_ip: 155.138.253.242
          ansible_user: root
          unity_relay_target_ip: 100.109.197.33
          unity_relay_ports:
            - 20101
